### ISSUE TITLE
always notify `Some npm packages are missing for this project, cannot display graph`

### ISSUE THREAD

**Issue by tjx666** [artT14/npm-dependancy-graph#1]
test project: https://github.com/tjx666/package-manager-enhancer/tree/main

![image](https://github.com/artT14/npm-dependancy-graph/assets/41773861/aed39f98-c490-46e6-8319-914c447417cd)

```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:58.115Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by artT14** [comment]
Problem: You need to have your npm packages installed in order to display the graph. 

Solution: Run `npm i` in the root of your project to install your packages and try again.

This is because, plugin utilizes the commands "npm ls --all --json" & "npm audit --json" in order to generate data to display graphs. Without installing the npm packages, it is not able to gather the necessary data.

Let me know if it works.

**Comment by tjx666** [comment]
I use pnpm, must use npm?

**Comment by artT14** [comment]
Yes, the plugin only works with `npm`. Admittedly, it might be nice to offer support for other package managers like `pnpm` and `yarn`.

**Comment by artT14** [comment]
Closing issue as pnpm/yarn are not supported
